<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Ulid" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DMP.Crosscutting\DMP.Crosscutting.csproj" />
    <ProjectReference Include="..\DMP.DataAccess\DMP.DataAccess.csproj" />
  </ItemGroup>

</Project>
